### Transforming Code into Idioatic Python
 - Replace traditional index manuplation with Python core looping idiomatic 

In [2]:
# Looping over a range of numbers 
for i in [0,1,2,3,4,5]:
    print(i**2,end =  " ")

0 1 4 9 16 25 

In [3]:
# Idiomatic Programming 
for i in range(6):
    print(i**2,end = " ")

0 1 4 9 16 25 

### Looping Over a Collection


In [4]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end = " ")

red green yellow purple 

In [5]:
for color in colors:
    print(color,end = " ")

red green yellow purple 

### Looping backwards

In [8]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end = " ")

purple yellow green red 

In [9]:
for color in reversed(colors):
    print(color,end = " ")

purple yellow green red 

### Looping in Sorted List

In [10]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end = " ")

green purple red yellow 

In [11]:
colors = ['red','green','yellow','purple']
for color in sorted(colors,reverse = True):
    print(color,end = " ")

yellow red purple green 

###
 - if x <= y and y <= z:
 - if x <= y <= z:
 - if x == True:
 - if x:
 

### Pandas

In [27]:
import pandas as pd

In [10]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [11]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [1]:
import os

In [ ]:
os.chdir("D:\\MyData\\") # Saves to certain Location

In [12]:
mydt.to_csv('WorkingFile.csv',index = False)

In [13]:
pwd

'/home/student'

### Reading the data from CSV file

In [28]:
mydata = pd.read_csv('WorkingFile.csv')

In [24]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [25]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=1,
                     names = ["CustId","Name","Company","Address"])

In [26]:
print(mydata1)

   CustId Name Company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [29]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],
                     names = ["CustId","Name","Company","Address"])

In [30]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


### Print Only Two Columns
### Print the large value from CustId column -- max
### Print the least value from CustId column -- min
### Average of CustId column -- sum(li)/len(li)

### Numpy Package
### Numpy - Working with Multi Dimensional array
 - Numpy arrays a bit like Python List
 - Numpy array is data structure of Numpy Lib
 - It's short name is Numeric Python or Numerical Python

In [31]:
import numpy as np # Import the numpy package

In [5]:
li = [1,2,3,4,5]
print(li,end = " ")

[1, 2, 3, 4, 5] 

In [7]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [32]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [33]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [35]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [7]:
def isPalindrome(n):
    rev=0
    buffer=n
    while n!=0:
        r=n%10
        rev=rev*10+r
        n=n//10
    if rev==buffer:
        return True
    else:
        return False
    return
def countPalindrome(lb,ub):
    cnt=0
    while lb!=ub:
        #implement
        if isPalindrome(lb)==True:
            cnt=cnt+1
        lb=lb+1
    return cnt
print(countPalindrome(1,10))
print(countPalindrome(11,100))

9
9


In [ ]:
import turtle as t
a1 = t.Turtle()
a1.pencolor('red')
for i in range(250):
    a1.forward(i*5)
    a1.left(91)
t.done()

In [5]:
def printlarge(n):
    large=0
    while n!=0:
        r=n%10
        if large<r:
            large=r
        n=n//10
    return large
print(printlarge(19528))
print(printlarge(36372))

9
7
